# i am infinite
# hello in this we are going to about if-elif-and else in python and their implementation so with no further delay let's start our programming journey
# a = 34
# the below one is an if ladder 
# if a>3:
#     print("the value of a is greater than 3")
# elif a>7:
#     print("the value of a is greater than 7")
# else:
#     print("the value of a is not greater than 7 or 3")
#  in the above ladder if if condition is met then the statement under is get executed if the if condition is false and elif condition is then the statement under it get executed but if both coditions are true than if dominates over elif and and if both conditions false then else statement is executed
# b = 34
# if a<3:
#     print("the value of b is lesser than 3")
# elif a>7:
#     print("the value of a is greater than 7")
# else:
#     print("the value is not lesser 3 and not greater than 7")
# c = 54
# if c<3:
#     print("the value of a is not lesser than 3")
# elif c<7:
#     print("the value of a is not lesser than 7")
# else:
#     print("the value of a is not lesser than 3 or 7")
# see finally we have built our ladder which meets with different things and we need to further explore it
# do not run the program by selecting something in the program if you do it retruns and error 

# if multiple statement
# a = 57
# if a>20:
#     print("a is greater than 20")
# if a<60:
#     print("a is lesser than 60")
# if a==57:
#     print("the value of a is 57")
# if a!=8:
#     print("the value of a is not equal to 8")
# if a==0:
#     print("the value of a is null")
# else:
#     print("the value of a is not zero")
# in these only last two statements form ladder and above statements are individual conditions and get implimented individually
# project 1
# a  = int(input("sir please enter your input: "))
# if a>=18:
#     print("yes")
# else:
#     print("no")
# relational operators in python are used to evaluate the conditions in if statements
# the examples of relational operators are >=,<=,==,!= etc.
a  = 56
if (a>25 and a<=60):
    print("you can work with us")
else:
    print("you cannot work with us")
# the above use logical operators namely and
# there are literally many thins in programming you need to learn