# mydict = {"mein":"me","koan":"who","kab":"when","kyoo":"why"}
# print("you can type following words ",mydict.keys())
# a = input("sir please enter your hindi word you want to find meaning for:")
# print(mydict[a])
# by typing the above line the program may throw error for the keys not in the dictionary so to avoid it we use get function
# print("the meaning of the hindi word is:",mydict.get(a))
# if the key you have input in the function is not there in the dictionary it input none and will not interrupt the program
# always understand the question do not say how much time you spent always see how much you have learnt it's one of the most important factor
# there are many functions in python
# PROJECT 2
# b = int(input("sir please enter the number:"))
# a = int(input("sir please enter the number:"))
# d = int(input("sir please enter the number:"))
# c = int(input("sir please enter the number:"))
# e = int(input("sir please enter the number:"))
# f = int(input("sir please enter the number:"))
# g = int(input("sir please enter the number:"))
# h = int(input("sir please enter the number:"))
# i = int(input("sir please enter the number:"))
# j = int(input("sir please enter the number:"))
# hello = {a,b,c,d,e,f,g,h,i,j}
# print(hello)
# sets are random and are mutable
# hellos = {18,"18"}
# print(hellos)
# a set can contain integers strings tuples relatively everything that is not hashable
# focus on small things because it is the small things that build a mega structure
# project 3
# s = set()
# s.add(20)
# s.add(20.0)
# s.add("20")
# print(s)
# focus on small things it makes a huge difference
# print(type(20))
# print(type(20.0))
# learn to solve real world projects
# project 4
# name1 = input("sir please enter your name: ")
# hello = input("sir enter the word(favourite language): ")
# name2 = input("sir please enter your name: ")
# hello1 = input("sir enter the word(favourite language): ")
# name3 = input("sir please enter your name: ")
# hello2 = input("sir enter the word(favourite language): ")
# name4 = input("sir please enter your name: ")
# hello3 = input("sir enter the word(favourite language): ")
# mydict = {name1:hello,name2:hello1,name3:hello2,name4:hello3}
# ba = input("sir please enter the name to show your favourite language: ")
# print("sir your favourite language is ",mydict[ba])
# you need to use program to do many thins
# do the work you love
# you can write the same program in many ways
# hello_shiva = {}
# a = input("sir please enter your favourite language: ")
# b = input("sir please enter your favourite language: ")
# c = input("sir please enter your favourite language: ")
# d = input("sir please enter your favourite language: ")
# hello_shiva["shiva"] = a
# hello_shiva["mahadev"] = b
# hello_shiva["ori"] = c
# hello_shiva["vishwa"] = d
# v = input("sir please enter the name to know your favourite language and you can query on that: ")
# print(hello_shiva[v])
# # remember you cannot change a value in a of a list in a set if the question is given which contains a set and it contains a list it is wrong
# example s = {1,2,3,4,5,[1,2]} it's a wrong set