# i am infinite
# HELLO IN THIS PROGRAM WE ARE GOING TO LEARN ABOUT IS AND IN FUNCTIONS
# a = [1,2,3]
# b=a
# print(a)
# print(b)
# c = list(a)
# print(c==a)
# print(c is a)

#  now let's dive into is and in operators
# a = 15
# b = 16
# print(a is b)
# p = [1,15,17]
# print(15 in p)
# in operators is one of the major operators we need to learn it is one of the things we need to have knowledge

# practice sheets

# a = input("sir please enter the number: ")
# b = input("sir please enter the number: ")
# c = input("sir please enter the number: ")
# d = input("sir please enter the number: ")
# if(a>b and a>c and a>d):
#     print("the greatest number according to our vision is: ",a)
# elif(b>a and b>c and b>d):
#     print("the greatest number according to our vision is: ",b)
# elif(c>a and c>b and c>d):
#     print("the greatest number according to our vision is: ",c)
# elif(d>a and d>b and d>c):
#     print("the greatest number according to our vision is: ",d)
# else:
#     print("no number is greatest according to our vision")
# there are many ways you can use or run the program programming is just logic and running the program by just using logic it is one of the things we can use to build many things
# the competition which is held for a purpose and a good reason always gives you the best results
# hello guys there is also another short way you can do the program
# 2nd program
# a = input("sir please enter the number: ")
# b = input("sir please enter the number: ")
# c = input("sir please enter the number: ")
# d = input("sir please enter the number: ")
# if (a>d):
#     hello = a
# else:
#     hello=d
# if b>c:
#     zen = b
# else:
#     zen = c
# if hello>zen:
#     print(hello," is the greatest number")
# else:
#     print(zen," is the greatest number")
# the above code is inspired by the cricket just take inspiration from many things it is one of the things you can do to make you code more good
# project 2

# just follow your curiousity

# num1 = int(input("sir please enter the marks of the first subject: "))
# num2 = int(input("sir please enter the marks of the second subject: "))
# num3 = int(input("sir please enter the marks of the third subject: "))
# if (num1>=33 and num2>=33 and num3>=33):
#     print("you have passed in individual subjects")
# else:
#     print("you have failed the individual subjects")
# if (num1+num2+num3)/3>=40:
#     print("you have passed the examination")
# PROJECT 3

# a = "make a lot of money"
# c = "subscribe this"
# d = "buy now"
# e = "click this"
# b = input("sir please enter the input: ")
# if (a in b and c in b and d in b and e in b):
#     print("this is a spam")
# else:
#     print("this is not a spam")
# a = "make a lot of money"
# c = "subscribe this"
# d = "buy now"
# e = "click this"
# b = input("sir please enter the input: ")
# spam = False
# if a in b:
#     spam=True
# elif c in b:
#     spam=True
# elif d in b:
#     spam=True
# elif e in b:
#     spam=True
# else:
#     spam=False
# if spam:
#     print("the comment is a spam")
# else:
#     print("the above one is not a spam")
# project 4
# finds the name given as input whether the input has less than 10 characters or not

# p = input("sir please enter you name: ")
# if len(p)<10:
#     print("you name has less than 10 letters")
# elif len(p)==10:
#     print("your name has ten letters")
# else:
#     print("your name has more than 10 letters")

# project 5

# a = ["mahakaal","shiva","rudra","mahadeva","rajesh"]
# ab = input("sir please enter your name: ")
# if ab in a:
#     print("sir your name is in the list")
# else:
#     print("your name is not in the list")

# project 6

# program to calculate the grade of the student using the marks of the student given as input

b = int(input("sir please enter the marks: "))
if b>=90 and b<=100:
    print("the grade of the student is excellent")
elif b>=80 and b<=90:
    print("your grade is A")
elif b>=70 and b<=80:
    print("your grade is B")
elif b>=60 and b<=70:
    print("your grade is C")
elif b>=50 and b<=60:
    print("your grade is D")
elif b<=50:
    print("your grade is F")
else:
    print("sorry error")
